module LuckyRecord::CallableErrorMessage
  abstract def call(name, value)
end